spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}
  cloud:
    config:
      fail-fast: false
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**,/api/v1/public/**,/api/v1/user/**
        - id: property-service
          uri: lb://property-service
          predicates:
            - Path=/api/landlord/**
        - id: tenant-service
          uri: lb://tenant-service
          predicates:
            - Path=/api/v1/tenant/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

cors:
  allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
